services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_api
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    network_mode: host
  tele:
    build:
      context: .
      dockerfile: Dockerfile_tele
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    network_mode: host
  lf:
    build:
      context: .
      dockerfile: Dockerfile_fetcher
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    network_mode: host